# Generated by Django 2.2.3 on 2019-07-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(default='', max_length=50)),
                ('last', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=150)),
                ('aboutyou', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
